### ISSUE TITLE
Todos/milestones?

### ISSUE THREAD

**Issue by eah13** [csev/pythonlearn#49]
I should be able to lend a hand with the conversion.  Looking at the repo and commit history, it's not immediately apparent what needs attention.  The TODO file gives a decent overview of what needs to be done but not, for instance, which files have been checked already and which still have issues.

Everyone's got their own product management prefs.  @csev: you're the guru for this repo.  Prefs?

I've seen checklist issues work for smaller stuff.  For example:

- [ ] This is a filename that needs conversion
- [x] This is a filename that is done.

The downside is they must be manually checked off by a committer.

I've also seen one issue per todo work.  A nice thing is that the issues can then be closed via the PR they address.  Also, they are very easy for contributors to pick up and knock out. 

Happy to chat synchronously if that's helpful.  Once some work is scoped I should be able to contribute every few days as I prep my course.

**Comment by alistairwalsh** [comment]
- [x] urljpeg.py
- [x] urllib1.py
- [x] urllib2.py
- [ ] urllink2.py
- [ ] urllink3.py
- [ ] urllinks.py
- [ ] urlregex.py
- [ ] urlwords.py

**Comment by alistairwalsh** [comment]
here's a full checklistlist

- [ ] argfile.py
- [ ] argtest.py
- [ ] avelist.py
- [ ] avenum.py
- [ ] average.py
- [ ] celsius.py
- [ ] copytildone.py
- [ ] count1.py
- [ ] count2.py
- [ ] count3.py
- [ ] curl1.py
- [ ] curl2.py
- [ ] curl3.py
- [ ] db1.py
- [ ] db2.py
- [ ] egg.py
- [ ] emaildb.py
- [ ] fahren.py
- [ ] geojson.py
- [ ] geoxml.py
- [ ] grade.py
- [ ] greet.py
- [ ] grep.py
- [ ] hidden.py
- [ ] json1.py
- [ ] json2.py
- [ ] largest.py
- [ ] mailcount.py
- [ ] mailtop.py
- [ ] oauth.py
- [ ] open.py
- [ ] pals.py
- [ ] pay.py
- [ ] pay2.py
- [ ] pay3.py
- [ ] re01.py
- [ ] re02.py
- [ ] re03.py
- [ ] re04.py
- [ ] re05.py
- [ ] re06.py
- [ ] re07.py
- [ ] re08.py
- [ ] re09.py
- [ ] re10.py
- [ ] re11.py
- [ ] re12.py
- [ ] re13.py
- [ ] re14.py
- [ ] search1.py
- [ ] search10.py
- [ ] search2.py
- [ ] search3.py
- [ ] search4.py
- [ ] search5.py
- [ ] search6.py
- [ ] search7.py
- [ ] search8.py
- [ ] search9.py
- [ ] sequence.py
- [ ] socket1.py
- [ ] socket2.py
- [ ] soft.py
- [ ] spamave.py
- [ ] twdump.py
- [ ] twfriends.py
- [ ] twitter1.py
- [ ] twitter2.py
- [ ] twjoin.py
- [ ] twspider.py
- [ ] twtest.py
- [ ] twurl.py
- [ ] txtcheck.py
- [ ] txtcheck2.py
- [ ] txtcheck3.py
- [ ] txtcount.py
- [ ] txtdelete.py
- [ ] txtmd5.py
- [ ] txtsize.py
- [ ] urljpeg.py
- [ ] urllib1.py
- [ ] urllib2.py
- [ ] urllink2.py
- [ ] urllink3.py
- [ ] urllinks.py
- [ ] urlregex.py
- [ ] urlwords.py
- [ ] whathour.py
- [ ] wikigrade.py
- [ ] wordlist.py
- [ ] words.py
- [ ] xml1.py
- [ ] xml2.py

**Comment by alistairwalsh** [comment]
and the code to create it

```python
from glob import glob

codefiles = glob('*.py')

with open('TODO.md','a') as fh: 

    for f in codefiles:
        print('- [ ] {}'.format(f), file = fh)
```

**Comment by eah13** [comment]
That's handy code for generating the empty list.  Once someone checks the boxes of what's been done already it's one version of what I was asking for.  But the bigger question is whether this is the workflow that @csev has in mind.  If so, let's run with it.

**Comment by csev** [comment]
Hey @eah13 do you want to be a committer?  Then you could check off the checklist and to PRs :)

**Comment by eah13** [comment]
Sure thing!  I'll make an issue with the list @alistairwalsh made and I (and any other committers) can check it as PRs get merged.  Each of the other bullets on TODO.md can get broken out and scoped as needed as we move along.  Say the word and I'll get going.

I've also spent some time getting my head around how things are laid out and the various make scripts for the book. As you can imagine, I'm interested in making a build script that uses Trinket to make all the code blocks in the text interactive.  :)

e.g. a code block like this:
```
>>> type(32)
<class 'int'>
```
becomes this, embedded inline in the HTML: https://trinket.io/python3/684055e075?outputOnly=true&runMode=console

Seems like this could be a different build pipeline ([kinda like you're already using?](https://github.com/csev/pythonlearn/blob/master/book/convert/pre.py#L49)) once you're building html again.  This wouldn't be able to be live anywhere without your permission but maybe with permission I could get a live build server up that I could use in class. 

If you're down with that I'll start researching it separately and will probably have a few questions for you about your conversion scripts.

**Comment by eah13** [comment]
Opened #60; closing this
