### ISSUE TITLE
Styling guide

### ISSUE THREAD

**Issue by MirzaI** [csev/pythonlearn#59]
Is there an official styling guide?

Seeing as the book is aimed at beginners, I would like the code samples to be as clear and beginner-friendly as possible.

Specifically, I would like to change all one liners such as:
`if re.search(search, line): count = count + 1`
into
```
if re.search(search, line):
    count = count + 1
```

Any thoughts?

**Comment by csev** [comment]
I like to mix it up and show that syntax when the if and its effect are really simple.   But I have been accepting pull requests that are cleaning up style.  

So I don't feel super strong either way.
