### ISSUE TITLE
Oauth & twitter examples direction?

### ISSUE THREAD

**Issue by eah13** [csev/pythonlearn#64]
We'll need a benevolent dictator (@csev) edict on this one I think.  oauth.py is abandoned and it seems like editing it directly is ill-advised.  There is [a successor](https://github.com/joestump/python-oauth2) but I haven't dug in to see how similar the API is.  Also, it's not a single file, so perhaps more confusing to include in the folder and have users import locally.

Backing up, how should the twitter examples be revised? There are some twitter-specific modules out there but they may be too high level for the chapter's goals.  Rewriting them to use `oauth2` seems like a good way forward but just wanted to check before heading down that road.  Some of the changes may be extensive (since Twitter also revised *its* API in the meantime) and may demand text tweaks.

**Comment by csev** [comment]
So I rewrote tall that code a while back (i.e. there is a code/old-twitter).  I would tend not to worry about the abandonedness of oauth.py unless it stops working.   I say keep it as simple as possible versys a quest to be more modern.  Unless what you are saying is that oauth.py won't work for Python 3 - that is something different.  SO I don't know the answer yet :)

**Comment by eah13** [comment]
That's the problem: oauth.py won't work for Python 3.  It would need a rewrite of unknown extent.

**Comment by csev** [comment]
Hmmm.   Then my first reaction is to eliminate Twitter from the book.  Frankly the only learning objective of that thread was a many-to-many relation - I can come up with a better example for that.

**Comment by eah13** [comment]
Alright. I may make a command line Twitter section for my course and if I'd be happy to contribute the code and update the chapter.  But it'd be a month or two before it was ready so if you get to rewriting before then go ahead..

**Comment by csev** [comment]
I just updated the oauth.py and tw*py files in code3.  I made oauth.py work in Python 3.0 and tweaked the tw*py files to deal with the new urllib stuff.   But it still needs some encodes and decodes.   So I think that we are 80% there.

**Comment by csev** [comment]
I added some decode() calls and the twitter apps are all working again.
