### ISSUE TITLE
Convert code blocks to VerbatimInput

### ISSUE THREAD

**Issue by eah13** [csev/pythonlearn#67]
As described in #63, we can automatically include the text of `code3` files in the text of the book using `\VerbatimInput{<filename>}`.  This now needs to happen for each chapter.

- [x] Chapter 1
- [x] Chapter 2
- [x] Chapter 3
- [x] Chapter 4
- [x] Chapter 5
- [x] Chapter 6
- [x] Chapter 7
- [x] Chapter 8
- [x] Chapter 9
- [x] Chapter 10
- [x] Chapter 11
- [x] Chapter 12
- [x] Chapter 13
- [x] Chapter 14
- [x] Chapter 15

**Comment by csev** [comment]
Finished them up.
