### ISSUE TITLE
Filenames for included code

### ISSUE THREAD

**Issue by eah13** [csev/pythonlearn#71]
For `\VerbatimInput` blocks it would be spiffy to have the filename listed above the code somehow for easy reference.

**Comment by csev** [comment]
Yup - I feel the need for a pipe and python file :)

**Comment by csev** [comment]
I just created a solution for this:

https://github.com/csev/pythonlearn/commit/d7fc29cd165b256e664a96b8f35ab3f93ab3f8c3

Feel free to alter it as you go forward.

**Comment by eah13** [comment]
+1 I like it.  Nice and simple
