### ISSUE TITLE
HTML build for class?

### ISSUE THREAD

**Issue by eah13** [csev/pythonlearn#73]
This is more of a convenience thing, but would it be possible to add an HTML version to the build server?  I'd like my students to be able to get the latest versions of chapters without re-downloading an epub.

Or, even better, can I get permission to set up a build server for my class that builds the latest into an HTML version?  I could password-protect it or make sure via the robots.txt it won't get indexed.  If we go with this option I can start experimenting with interactive Trinket code blocks for the book

**Comment by csev** [comment]
Feel free to run your own build server and trinketize it all - don't hide it - I will happily point to it.  At some point, if you make it work, I may add a build server as well.  If we could teach Trinket to do grading and Python 3.0, then maybe I would get really lazy and just use Trinket in my Coursera courses :)

**Comment by eah13** [comment]
Thanks!  Working on this now.  Will post links when things are cleaned up.
