### ISSUE TITLE
Chapter numbers?

### ISSUE THREAD

**Issue by eah13** [csev/pythonlearn#79]
Should intro be Ch 0 or Ch 1?  If 0, can I rename the files to match?  Trying to avoid confusion.

**Comment by csev** [comment]
No - I need to reset that somehow.  The preface should be an un-numbered chapter - it appears in the table of contents by mistake.  The idea of the HTML and EPUB versions is not to include the preface at the beginning - instead do so at the very end.  That is why the preface is "A1" and book.sh pulls it to the beginning for the PDF and puts it at the end in the EPUB.
