### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by eah13** [csev/pythonlearn#83]
I've started using Travis CI for my class website and it's pretty great.  Wondering if tests for this repo would be a good idea?  Would ensure that PRs don't break builds.  Downside: Waiting a few minutes when a PR gets submitted to see if it passes.

Initially it could just check that `book.sh` builds with no errors but eventually could check the html version, website, etc.  https://github.com/gjtorikian/html-proofer or something similar could check for dead links, etc.

**Comment by eah13** [comment]
another downside: keeping the tests in sync with any build workflow changes over time.

**Comment by csev** [comment]
I like the idea.   I was thinking of building a set of tests for code3 - it would not be hard to cover most of those tests.  I am so not an expert in this space though.  We use Travis in Sakai and it is great but someone smarter than me set it up.

**Comment by eah13** [comment]
I know barely enough to be dangerous with travis.  May give it a go in a few weeks if you haven't gotten to it yet.

**Comment by csev** [comment]
I added a unit3 folder - you

    cd unit3
    python3 unit.py

And it runs unt tests on the code.   Still no unit tests for the HTML.

**Comment by csev** [comment]
I just added a .travis.yml - I am clueless.  It only tests the unit3/unit.py

**Comment by csev** [comment]
I checked in a broken bit of code and travis caught it - and then checked in a new bit of code and travis was happy.  Now I can evolve the unit.sh file and do more testing like autobuilding the book and html and catching errors.

**Comment by eah13** [comment]
Nice!  I'm a travis novice too but from what I see all's in order.  It's very extensible- we can essentially run any and all scripts.  Once this grant is done I'll dive back in and hook up HTML to travis if you haven't yet.
